// frontend/src/components/SessionList.tsx
import React from 'react';
import { Session, SessionStatus } from '../types';

interface SessionListProps {
  sessions: Session[];
  activeSessionId: string | null;
  onSessionSelect: (sessionId: string) => void;
  onCreateSession: () => void;
  onDeleteSession: (sessionId: string) => void;
  isLoading: boolean;
}

const SessionList: React.FC<SessionListProps> = ({
  sessions,
  activeSessionId,
  onSessionSelect,
  onCreateSession,
  onDeleteSession,
  isLoading
}) => {
  // Get a human-readable status with icon
  const getStatusDisplay = (status: string) => {
    switch(status) {
      case SessionStatus.Created:
        return <span className="text-gray-500">●</span>;
      case SessionStatus.Recording:
        return <span className="text-red-500 animate-pulse">⬤</span>;
      case SessionStatus.Processing:
        return <span className="text-yellow-500">⬤</span>;
      case SessionStatus.Completed:
        return <span className="text-green-500">✓</span>;
      case SessionStatus.Error:
        return <span className="text-red-500">✕</span>;
      default:
        return <span className="text-gray-500">●</span>;
    }
  };
  
  // Format created_at date
  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleTimeString();
  };
  
  // Get session name/label
  const getSessionName = (session: Session, index: number) => {
    const shortId = session.session_id.substring(0, 6);
    
    if (session.status === SessionStatus.Recording) {
      return `Recording... (${shortId})`;
    }
    
    if (session.status === SessionStatus.Processing) {
      return `Processing... (${shortId})`;
    }
    
    return `Session ${index + 1} (${shortId})`;
  };

  return (
    <div className="bg-white shadow rounded-lg p-4 mb-6">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-lg font-medium text-gray-900">Sessions</h2>
        <button
          onClick={onCreateSession}
          disabled={isLoading}
          className="px-3 py-1 bg-blue-500 text-white text-sm rounded hover:bg-blue-600 disabled:bg-blue-300"
        >
          New Session
        </button>
      </div>

      {sessions.length === 0 ? (
        <div className="text-gray-500 text-center py-4">
          {isLoading ? 'Loading sessions...' : 'No sessions available. Create one to start.'}
        </div>
      ) : (
        <div className="overflow-auto max-h-60">
          <ul className="divide-y divide-gray-200">
            {sessions.map((session, index) => (
              <li key={session.session_id} className={`py-2 px-1 cursor-pointer hover:bg-gray-50 ${session.session_id === activeSessionId ? 'bg-blue-50' : ''}`}>
                <div className="flex items-center justify-between" onClick={() => onSessionSelect(session.session_id)}>
                  <div className="flex items-center space-x-2">
                    <div className="w-4">{getStatusDisplay(session.status)}</div>
                    <div className="flex-1 truncate">{getSessionName(session, index)}</div>
                    <div className="text-xs text-gray-500">{formatDate(session.created_at)}</div>
                  </div>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      onDeleteSession(session.session_id);
                    }}
                    className="text-red-500 hover:text-red-700 text-sm"
                  >
                    Delete
                  </button>
                </div>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};

export default SessionList;

// src/lib/components/SessionList.svelte
<script lang="ts">
	import { sessionState } from '$lib/stores/session.svelte.js';
	import type { SessionSummary } from '$lib/types/index.js';

	const statusBadge: Record<string, string> = {
		created: 'bg-gray-700 text-gray-300',
		recording: 'bg-red-900 text-red-300',
		processing: 'bg-yellow-900 text-yellow-300',
		completed: 'bg-green-900 text-green-300',
		error: 'bg-red-900 text-red-300'
	};

	function formatDate(dateStr: string): string {
		const d = new Date(dateStr);
		return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
	}

	async function handleNew() {
		await sessionState.createSession();
	}

	async function handleSelect(session: SessionSummary) {
		await sessionState.selectSession(session.id);
	}

	async function handleDelete(e: Event, sessionId: string) {
		e.stopPropagation();
		await sessionState.deleteSession(sessionId);
	}

	$effect(() => {
		sessionState.loadSessions();
	});
</script>

<div class="space-y-2">
	<button
		onclick={handleNew}
		class="w-full px-3 py-2 text-sm rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-medium transition-colors"
	>
		New Session
	</button>

	{#if sessionState.loading}
		<p class="text-gray-500 text-sm px-2">Loading...</p>
	{/if}

	<div class="space-y-1">
		{#each sessionState.sessions as session}
			<!-- svelte-ignore a11y_no_static_element_interactions -->
			<div
				onclick={() => handleSelect(session)}
				onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') handleSelect(session); }}
				role="button"
				tabindex="0"
				class="w-full text-left px-3 py-2 rounded-lg transition-colors cursor-pointer
					{sessionState.activeSession?.id === session.id
					? 'bg-gray-800 border border-gray-600'
					: 'hover:bg-gray-800/50'}"
			>
				<div class="flex items-center justify-between">
					<span class="text-sm font-medium text-gray-200 truncate">{session.name}</span>
					<button
						onclick={(e) => handleDelete(e, session.id)}
						class="text-gray-600 hover:text-red-400 text-xs px-1 transition-colors"
						title="Delete session"
					>
						x
					</button>
				</div>
				<div class="flex items-center gap-2 mt-1">
					<span class="text-xs px-1.5 py-0.5 rounded {statusBadge[session.status] ?? statusBadge.created}">
						{session.status}
					</span>
					<span class="text-xs text-gray-500">{formatDate(session.created_at)}</span>
				</div>
			</div>
		{/each}

		{#if sessionState.sessions.length === 0 && !sessionState.loading}
			<p class="text-gray-500 text-sm text-center py-4">No sessions yet</p>
		{/if}
	</div>
</div>
